name: CI

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
    branches: [master]

permissions:
  contents: read
  checks: read

jobs:
  quality:
    name: Quality and coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis. This is needed for better sonar

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest

      - name: Format Check
        run: deno task format:check

      - name: Lint
        run: deno task lint

      - name: Tests & Coverage
        run: deno task test:coverage

      - name: Coverage Report
        run: deno task coverage:report

      - name: Check for SonarCloud Token Availability
        id: sonar-token
        shell: bash
        run: |
          if [ "${{ secrets.SONAR_TOKEN }}" != '' ]; then
            echo "available=true" >> $GITHUB_OUTPUT;
          else
            echo "available=false" >> $GITHUB_OUTPUT;
          fi

      - name: SonarCloud Code Analysis
        if: ${{ steps.sonar-token.outputs.available == 'true' && github.repository == 'poolifier/poolifier-web-worker' }}
        uses: sonarsource/sonarqube-scan-action@v8.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  runtime-tests:
    name: Deno ${{ matrix.deno }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            deno: latest
            experimental: false
          - os: macos-latest
            deno: latest
            experimental: false
          - os: ubuntu-latest
            deno: lts
            experimental: false
          - os: ubuntu-latest
            deno: canary
            experimental: true

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Deno ${{ matrix.deno }}
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Tests
        run: deno task test

  bundle:
    name: Bundle on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Bundle
        run: deno task bundle
